# Use an official Node.js runtime as the base image
FROM node:22.13.1

LABEL authors="Fazrul"

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json /app/

# Install app dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the React app for production
RUN npm run build

# Expose port 3001 to the outside world
EXPOSE 3001

# Command to start the React app
CMD ["serve", "-s", "build", "-l", "3001"]
